create database OrderManagement;
show tables;
describe series;
describe model;
create table series(seriesId Integer(20),seriesName varchar(20));
INSERT into series Values('3','Series 3');
select * from series;
ALTER TABLE series DROP COLUMN series_name;
alter table color change column price  colorprice Integer(20);
rename table ordercreate to ordermanage;
create table model(modelName varchar(20), seriesId integer(20), modelId integer(20),foreign key (seriesId) references series(seriesId));
alter table series add primary key(seriesid);
INSERT into model Values('Model 6','3','6');
delete from model where modelName ='Model 2';
select * from model;
alter table model add column modelId integer(20);
alter table model add primary key(modelId);
insert into model (modelId) values('1');
drop table model;
create table accessory(accessoryName varchar(20), accessoryId integer(20), modelId integer(20),foreign key (modelId) references model(modelId));
alter table accessory add primary key(accessoryId);
INSERT into accessory Values('a12','12','6');
select * from accessory;
create database OrderManagement;
show tables;
describe series;
INSERT into series Values('3','Series 3');
select * from series;
create table model(modelName varchar(20), seriesId integer(20), modelId integer(20),foreign key (seriesId) references series(seriesId));
alter table series add primary key(seriesId);
INSERT into model Values('Model 6','3','6');
delete from model where modelName ='Model 2';
select * from model;
alter table color add column price integer(20);
alter table model add primary key(modelId);
insert into model (price) values(11);
update color set colorprice ="500" where colorid = 1;
update color set colorprice= 950 where colorid =12;
drop table model;
create table accessory(accessoryName varchar(20), accessoryId integer(20), modelId integer(20),foreign key (modelId) references model(modelId));
alter table accessory add primary key(accessoryId);
INSERT into accessory Values('a12','12','6');
select * from accessory;
create table color(colorName varchar(20), colorId integer(20), modelId integer(20),foreign key (modelId) references model(modelId));
INSERT into color Values('c12','12','6');
create table orderCreate(seriesName varchar(20), modelName varchar(20),accessoryName varchar(20),colorName varchar(20));
alter table orderCreate add column orderId integer(20);
create table userProfile(userName varchar(20), userId varchar(20));

select * from color;
select * from orderCreate;
select * from ordermanage;
select * from userProfile;

